format_version: 3
pipelines:
  "gocd-yaml-plugin":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git: https://github.com/vikybansod/gocd.git
      branch: main
    stages:
      - build:
          clean_workspace: true
          resources:
            - docker
          artifacts:
           - build:
               source: build/libs/*.jar
               destination: build/libs
          tasks:
           - exec:
               command: bash
               arguments:
                - -c
                - ./tasks.sh build
      - bump:
          clean_workspace: true
          jobs:
            patch:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - ./tasks.sh
                      - set_version
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh commit
                - exec:
                    command: git
                    arguments:
                      - push
                      - origin
                      - master