format_version: 3
pipelines:
  "gocd-yaml-plugin":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        git: git@github.com:tomzo/gocd-yaml-config-plugin.git
        blacklist:
          - README.md
    stages:
      - build:
          clean_workspace: true
          resources:
            - docker
          artifacts:
           - build:
               source: build/libs/*.jar
               destination: build/libs
          tasks:
           - exec:
               command: bash
               arguments:
                - -c
                - ./tasks.sh build
      - release:
          approval: manual
          clean_workspace: true
          jobs:
            github:
              resources:
                - docker
              secure_variables:
                GITHUB_TOKEN: "AES:+QBztHVft9PmbwLLgpXvhA==:QHWQ+Ya2aJF2HoYo2G6LGlb2thWekhXiO626YKcEfeCw0IH7ornkOf7F91+RetOY"
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: build/libs
                    destination: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - ./tasks.sh
                      - github_release
      - bump:
          clean_workspace: true
          jobs:
            patch:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - ./tasks.sh
                      - set_version
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh commit
                - exec:
                    command: git
                    arguments:
                      - push
                      - origin
                      - master