format_version: 3
pipelines:
  p1:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/vikybansod/gocd.git
        branch: main
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                command: pwd
                run_if: passed
    - stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                  - -c
                  - echo "test"
                run_if: passed
  p1_dev:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/vikybansod/gocd.git
        branch: main
      p1:
        pipeline: p1
        stage: stage2
        name: p1
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                  - -c
                  - echo "test"
                run_if: passed
  p2_dev:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/vikybansod/gocd.git
        branch: master
      p1:
        pipeline: p1
        stage: stage2
        name: p1
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                  - -c
                  - echo "test"
                run_if: passed
  p2_qa:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/vikybansod/gocd.git
        branch: master
      p2_dev:
        pipeline: p2_dev
        stage: stage1
        name: p2_dev
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                  - -c
                  - echo "test"
                run_if: passed    