format_version: 10
pipelines:
  p2_test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-eecd411:
        git: https://github.com/vikybansod/gocd.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - s1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          j1:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - --help
                command: kubectl
                run_if: passed
